### PR TITLE
Fix a bug where GetBlockFees would always return an empty fee for the current height

### PR DESCRIPTION
**Pull request by davepuchyr**

### CODE REVIEW

**Comment by davepuchyr** [comment]
@LeCodeurDuDimanche , I run `starnamed` locally after hacking `NumBlocksInAWeek uint64 = 100` in querier.go and get

```
3:41PM ERR CONSENSUS FAILURE!!! err="negative coin amount" module=consensus stack="goroutine 74 [running]:
runtime/debug.Stack()
   runtime/debug/stack.go:24 +0x65
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
   github.com/tendermint/tendermint@v0.34.10/consensus/state.go:726 +0x4c
panic({0x17adf60, 0x1f17910})
   runtime/panic.go:1038 +0x215
github.com/cosmos/cosmos-sdk/types.Coins.Sub(...)
   github.com/cosmos/cosmos-sdk@v0.42.5/types/coin.go:334
github.com/iov-one/starnamed/x/starname/keeper.Keeper.addOrRemoveFeesSum({{0x1f845e0, 0xc00023fce0}, {0x7f9578431f48, 0xc0008134a0}, {0x1f3e4c0, 0xc0001e1170}, {0x1f3e6c0, 0xc000efebb0}, {0x1f3e520, 0xc00037e840}, ...}, ...)
   github.com/iov-one/starnamed/x/starname/keeper/keeper.go:132 +0x174
github.com/iov-one/starnamed/x/starname/keeper.Keeper.GetBlockFeesSum({{0x1f845e0, 0xc00023fce0}, {0x7f9578431f48, 0xc0008134a0}, {0x1f3e4c0, 0xc0001e1170}, {0x1f3e6c0, 0xc000efebb0}, {0x1f3e520, 0xc00037e840}, ...}, ...)
   github.com/iov-one/starnamed/x/starname/keeper/keeper.go:170 +0x1e5
github.com/iov-one/starnamed/x/starname/keeper.Keeper.RefreshBlockSumCache(...)
   github.com/iov-one/starnamed/x/starname/keeper/keeper.go:120
github.com/iov-one/starnamed/x/starname.EndBlocker(...)
   github.com/iov-one/starnamed/x/starname/abci.go:12
github.com/iov-one/starnamed/x/starname.AppModule.EndBlock(...)
   github.com/iov-one/starnamed/x/starname/module.go:127
github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x1f7a428, 0xc000040100}, {0x1f9f478, 0xc005a55b40}, {{0xb, 0x0}, {0xc0053f8030, 0x10}, 0x135, ...}, ...}, ...)
   github.com/cosmos/cosmos-sdk@v0.42.5/types/module/module.go:354 +0x302
github.com/iov-one/starnamed/app.(*WasmApp).EndBlocker(...)
   github.com/iov-one/starnamed/app/app.go:593
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc000198d00, {0x100000000000020})
   github.com/cosmos/cosmos-sdk@v0.42.5/baseapp/abci.go:196 +0x23d
github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc000ea4960, {0xc000ea4960})
   github.com/tendermint/tendermint@v0.34.10/abci/client/local_client.go:282 +0xdf
github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc00551ec80, {0x20})
   github.com/tendermint/tendermint@v0.34.10/proxy/app_conn.go:89 +0x24
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x1f7b030, 0xc000dfe180}, {0x1f8ed50, 0xc000da5330}, 0xc004d685a0, {0x1f9f618, 0xc000da4770}, 0x134)
   github.com/tendermint/tendermint@v0.34.10/state/execution.go:327 +0x54e
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc0000c5c40, 0x10}, 0x1, 0x134, {{0xc005385de0, ...}, ...}, ...}, ...)
   github.com/tendermint/tendermint@v0.34.10/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000e2c000, 0x135)
   github.com/tendermint/tendermint@v0.34.10/consensus/state.go:1635 +0x9fd
github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000e2c000, 0x135)
   github.com/tendermint/tendermint@v0.34.10/consensus/state.go:1546 +0x305
github.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()
   github.com/tendermint/tendermint@v0.34.10/consensus/state.go:1481 +0x87
github.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc000e2c000, 0x135, 0x0)
   github.com/tendermint/tendermint@v0.34.10/consensus/state.go:1519 +0xc06
github.com/tendermint/tendermint/consensus.(*State).addVote(0xc000e2c000, 0xc005a6c0a0, {0x0, 0x0})
   github.com/tendermint/tendermint@v0.34.10/consensus/state.go:2132 +0xb6e
github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000e2c000, 0xc005a6c0a0, {0x0, 0xc004ecbbb8})
   github.com/tendermint/tendermint@v0.34.10/consensus/state.go:1930 +0x2c
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000e2c000, {{0x1f3c0a0, 0xc0046d2010}, {0x0, 0x0}})
   github.com/tendermint/tendermint@v0.34.10/consensus/state.go:838 +0x3dc
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000e2c000, 0x0)
   github.com/tendermint/tendermint@v0.34.10/consensus/state.go:782 +0x512
created by github.com/tendermint/tendermint/consensus.(*State).OnStart
   github.com/tendermint/tendermint@v0.34.10/consensus/state.go:378 +0x12f
"
Please investigate.

**Comment by davepuchyr** [comment]
> @LeCodeurDuDimanche , I run `starnamed` locally after hacking `NumBlocksInAWeek uint64 = 100` in querier.go and get
> 
> ```
> 3:41PM ERR CONSENSUS FAILURE!!! err="negative coin amount" module=consensus stack="goroutine 74 [running]:
> ```

To give a little more context, I started the node, ran the integration tests, then kept the node running without it executing any more txs so that slidingSum.feesSum should have been 0 and not gone negative.

**Comment by LeCodeurDuDimanche** [comment]
@davepuchyr I am not able to reproduce this bug on the branch `patch-yield`. Are you able to reproduce it ?
Maybe, if you haven't re-run the node since, you can send me your `data` folder for further inspection ?

**Comment by davepuchyr** [comment]
> @davepuchyr I am not able to reproduce this bug on the branch `patch-yield`. Are you able to reproduce it ? Maybe, if you haven't re-run the node since, you can send me your `data` folder for further inspection ?

Please use the `yield-patch` branch.  It is cherry-picked from your `patch-yield` branch but branched off of the `v0.10.x` branch and allows us to use PRs (like this one :) ).

I cannot consistently reproduce the bug, but it took down our `stargatenet` testnet yesterday.

I suspect that the problem is due to floating point arithmetic.  We need to make sure that when the last block that contains a fee is removed from `slidingSum.feesSum` that that fee is not greater than the `slidingSum.feesSum`, ie I think the negative coin panic is due to an amount the size of the machine epsilon.

**Comment by LeCodeurDuDimanche** [comment]
> > @davepuchyr I am not able to reproduce this bug on the branch `patch-yield`. Are you able to reproduce it ? Maybe, if you haven't re-run the node since, you can send me your `data` folder for further inspection ?
> 
> Please use the `yield-patch` branch. It is cherry-picked from your `patch-yield` branch but branched off of the `v0.10.x` branch and allows us to use PRs (like this one :) ).
> 
> I cannot consistently reproduce the bug, but it took down our `stargatenet` testnet yesterday.
> 
> I suspect that the problem is due to floating point arithmetic. We need to make sure that when the last block that contains a fee is removed from `slidingSum.feesSum` that that fee is not greater than the `slidingSum.feesSum`, ie I think the negative coin panic is due to an amount the size of the machine epsilon.

Arf, I didn't notice the difference between the two branch.
Regarding floating point arithmetic, we only use integers and no decimal data (we have only amounts mutiple of 1 `uiov`).

**Comment by davepuchyr** [comment]
> Arf, I didn't notice the difference between the two branch. Regarding floating point arithmetic, we only use integers and no decimal data (we have only amounts mutiple of 1 `uiov`).

Ah, right, Coin uses a wrapped 256-bit int.  I was thinking DecCoin.  

Anyway, do you have any idea why we might get a negative coin amount?

**Comment by LeCodeurDuDimanche** [comment]
> Anyway, do you have any idea why we might get a negative coin amount?

For now I have no clue, I'm trying to replicate the bug to find out

**Pull request merged**
